version: "3"

services:
  uwazi:
    build: ./
    user: "node"
    working_dir: /home/node/uwazi
    ports:
      - 3000:3000
    command: "yarn production-build"
    #networks:
    #  - exposed
    depends_on:
      - elasticsearch
      - mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    restart: unless-stopped
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    # TODO: close these ports (fititnt, 2018-04-14 10:22 BRT)
    ports:
      - 9200:9200

  mongo:
    image: mongo:3.4
    restart: unless-stopped
    volumes:
     - ./data/mongo:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles
    ports:
      - 27017:27017
    logging:
      options:
        max-size: 10m
        max-file: '3'

  # Cross-platform and self hosted, easy to use mongodb management tool - Formerly Mongoclient
  # See https://github.com/nosqlclient/nosqlclient
  mongo-gui-mongoclient:
    image: mongoclient/mongoclient:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - 51000:3000

volumes:
  esdata1:
    driver: local



